blank_issues_enabled: false
contact_links:
  - name: Supernova Developer Community
    url: https://community.supernova.io/
    about: Ask and answer all your questions in our community of like-minded developers.