name: "⭐ New Helper Request"
description: Suggest a new helper that everyone writing exporters will benefit from
labels: ["helper", "feature request"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping us making the developer experience better by providing your idea for improvement! Please update the title above to describe your idea at glance.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please provide the detailed description of your idea. 
    validations:
      required: true
  - type: textarea
    id: code-example
    attributes:
      label: Code Example
      description: |
        Consider adding code examples to explain it better. If you already have specific implementation in mind, please provide it as well.
    validations:
      required: false